import { getRecommendation } from './simulation-helpers'
import type { Issue, Module } from '@/types'

export interface ExportReportData {
  projectName?: string
  score: number
  summary: string
  stack: string[]
  modules?: Module[] | Array<{ name: string; risk: string; files: number }>
  issues?: Issue[]
  baseCost: number
}

/**
 * Generate formatted Markdown for release readiness report
 */
export function generateMarkdownReport(data: ExportReportData): string {
  const { projectName, score, summary, stack, modules, issues, baseCost } = data
  const riskLevel = score > 70 ? 'CRITICAL' : score > 40 ? 'HIGH' : score > 20 ? 'MODERATE' : 'LOW'
  const generatedAt = new Date().toLocaleString()

  let md = `# DryRun — Release Readiness & Deployment Report\n\n`
  md += `**Project:** ${projectName || 'Unknown Project'}\n`
  md += `**Generated:** ${generatedAt}\n`
  md += `**Release Risk Score:** ${score}/100 (${riskLevel} RISK)\n`
  md += `**Estimated Incident Blast Radius:** $${baseCost.toLocaleString()}\n`
  md += `**Engine:** IBM watsonx.ai Granite 3.3 8B Instruct\n\n`

  md += `## 1. Executive Summary & Assessment\n\n`
  md += `${summary || 'No summary available.'}\n\n`

  if (stack && stack.length > 0) {
    md += `## 2. Technology Stack & Analyzed Services\n\n`
    md += stack.map(s => `- ${s}`).join('\n') + '\n\n'
  }

  if (modules && modules.length > 0) {
    md += `## 3. Architecture & Module Breakdown\n\n`
    md += `| Module | Risk Level | Files |\n`
    md += `|---|---|---|\n`
    md += modules.map(m => `| ${m.name} | ${m.risk.toUpperCase()} | ${m.files} |`).join('\n') + '\n\n'
  }

  if (issues && issues.length > 0) {
    md += `## 4. Deployment Gates & Identified Vulnerabilities\n\n`
    issues.forEach((issue, idx) => {
      const typeStr = issue.type?.toUpperCase() || 'GENERAL'
      const sevStr = issue.severity?.toUpperCase() || 'INFO'
      const rec = getRecommendation(issue.type, issue.severity)

      md += `### ${idx + 1}. [${sevStr}] ${typeStr}\n\n`
      md += `**Finding:** ${issue.description}\n\n`
      md += `**Impact:** ${issue.impact}\n\n`
      md += `**Mitigation Recommendation:** ${rec}\n\n`
    })
  }

  md += `---\n*Generated by DryRun — Pre-Flight Release Simulation Engine (watsonx.ai)*\n`
  return md
}

/**
 * Triggers browser download of Markdown report
 */
export function exportMarkdown(data: ExportReportData): void {
  const md = generateMarkdownReport(data)
  const slug = (data.projectName || 'release').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
  const fileName = `dryrun-release-notes-${slug}-${timestamp}.md`

  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' })
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.download = fileName
  link.click()
  URL.revokeObjectURL(link.href)
}

/**
 * Triggers client-side generation & download of PDF report via jsPDF
 */
export async function exportPdf(data: ExportReportData): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const { projectName, score, summary, stack, modules, issues, baseCost } = data

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 14
  const contentWidth = pageWidth - margin * 2

  let y = 16

  const ensureSpace = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - 16) {
      doc.addPage()
      y = 16
    }
  }

  // 1. Branding Header
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(20, 20, 19)
  doc.text('DRYRUN', margin, y)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(110, 110, 105)
  doc.text('PRE-FLIGHT RELEASE READINESS & DEPLOYMENT DOSSIER', margin + 30, y - 0.5)

  y += 5
  doc.setDrawColor(0, 0, 0)
  doc.setLineWidth(0.35)
  doc.line(margin, y, pageWidth - margin, y)
  y += 6

  // 2. Metadata
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(20, 20, 19)
  doc.text(`Project: ${projectName || 'Unknown Repository'}`, margin, y)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - margin, y, { align: 'right' })
  y += 6

  // 3. KPI / Score Card (Neo-Brutalist Box)
  ensureSpace(24)
  const riskLevel = score > 70 ? 'CRITICAL RISK' : score > 40 ? 'DEGRADED RISK' : 'NOMINAL'
  const scoreColorRgb = score > 70 ? [220, 38, 38] : score > 40 ? [217, 119, 6] : [22, 163, 74]

  doc.setDrawColor(0, 0, 0)
  doc.setLineWidth(0.4)
  doc.setFillColor(247, 246, 242)
  doc.roundedRect(margin, y, contentWidth, 20, 2, 2, 'FD')

  // Score column
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(110, 110, 105)
  doc.text('RELEASE RISK SCORE', margin + 6, y + 6)

  doc.setFontSize(13)
  doc.setTextColor(scoreColorRgb[0], scoreColorRgb[1], scoreColorRgb[2])
  doc.text(`${score} / 100 (${riskLevel})`, margin + 6, y + 14)

  // Blast radius column
  doc.setFontSize(8)
  doc.setTextColor(110, 110, 105)
  doc.text('ESTIMATED INCIDENT BLAST RADIUS', margin + contentWidth / 2, y + 6)

  doc.setFontSize(13)
  doc.setTextColor(20, 20, 19)
  doc.text(`$${baseCost.toLocaleString()}`, margin + contentWidth / 2, y + 14)

  y += 26

  // 4. Executive Summary
  ensureSpace(20)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(20, 20, 19)
  doc.text('1. Executive Summary & Assessment', margin, y)
  y += 5

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(50, 50, 50)
  const summaryLines = doc.splitTextToSize(summary || 'No summary generated.', contentWidth)
  ensureSpace(summaryLines.length * 4.2)
  doc.text(summaryLines, margin, y)
  y += summaryLines.length * 4.2 + 6

  // 5. Tech Stack
  if (stack && stack.length > 0) {
    ensureSpace(14)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(20, 20, 19)
    doc.text('2. Technology Stack & Analyzed Services', margin, y)
    y += 5

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8.5)
    doc.setTextColor(50, 50, 50)
    const stackText = stack.join('  •  ')
    const stackLines = doc.splitTextToSize(stackText, contentWidth)
    ensureSpace(stackLines.length * 4.2)
    doc.text(stackLines, margin, y)
    y += stackLines.length * 4.2 + 6
  }

  // 6. Architecture & Modules
  if (modules && modules.length > 0) {
    ensureSpace(18)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(20, 20, 19)
    doc.text('3. Architecture & System Modules', margin, y)
    y += 5

    doc.setFillColor(240, 239, 235)
    doc.rect(margin, y, contentWidth, 5, 'F')
    doc.setFontSize(8)
    doc.setTextColor(80, 80, 80)
    doc.text('MODULE NAME', margin + 4, y + 3.5)
    doc.text('RISK STATUS', margin + contentWidth - 45, y + 3.5)
    doc.text('FILES', margin + contentWidth - 14, y + 3.5)
    y += 6

    modules.forEach((mod) => {
      ensureSpace(6)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.setTextColor(30, 30, 30)
      doc.text(mod.name, margin + 4, y + 3)

      const modRisk = mod.risk.toUpperCase()
      if (modRisk === 'DANGER') doc.setTextColor(220, 38, 38)
      else if (modRisk === 'WARN') doc.setTextColor(217, 119, 6)
      else doc.setTextColor(22, 163, 74)
      doc.text(modRisk, margin + contentWidth - 45, y + 3)

      doc.setTextColor(100, 100, 100)
      doc.text(String(mod.files), margin + contentWidth - 14, y + 3)

      doc.setDrawColor(230, 228, 222)
      doc.setLineWidth(0.2)
      doc.line(margin, y + 4.5, margin + contentWidth, y + 4.5)
      y += 5.5
    })
    y += 4
  }

  // 7. Deployment Gates & Identified Vulnerabilities
  if (issues && issues.length > 0) {
    ensureSpace(20)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(20, 20, 19)
    doc.text('4. Deployment Gates & Identified Vulnerabilities', margin, y)
    y += 6

    issues.forEach((issue, idx) => {
      const typeStr = issue.type?.toUpperCase() || 'FINDING'
      const sevStr = issue.severity?.toUpperCase() || 'INFO'
      const rec = getRecommendation(issue.type, issue.severity)

      const findingLines = doc.splitTextToSize(`Finding: ${issue.description}`, contentWidth - 8)
      const impactLines = doc.splitTextToSize(`Impact: ${issue.impact}`, contentWidth - 8)
      const recLines = doc.splitTextToSize(`Mitigation: ${rec}`, contentWidth - 8)

      const boxHeight = 10 + (findingLines.length + impactLines.length + recLines.length) * 3.8 + 4

      ensureSpace(boxHeight + 4)

      // Box container
      doc.setDrawColor(210, 208, 200)
      doc.setLineWidth(0.3)
      doc.setFillColor(252, 251, 249)
      doc.roundedRect(margin, y, contentWidth, boxHeight, 1.5, 1.5, 'FD')

      // Severity Tag
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      if (sevStr === 'CRITICAL') doc.setTextColor(220, 38, 38)
      else if (sevStr === 'HIGH') doc.setTextColor(234, 88, 12)
      else if (sevStr === 'MEDIUM' || sevStr === 'MODERATE') doc.setTextColor(217, 119, 6)
      else doc.setTextColor(59, 130, 246)

      doc.text(`[${sevStr}] ${typeStr} #${idx + 1}`, margin + 4, y + 5)

      let innerY = y + 9.5
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(7.5)
      doc.setTextColor(30, 30, 30)
      doc.text(findingLines, margin + 4, innerY)
      innerY += findingLines.length * 3.8

      doc.setTextColor(180, 50, 50)
      doc.text(impactLines, margin + 4, innerY)
      innerY += impactLines.length * 3.8

      doc.setTextColor(30, 120, 70)
      doc.text(recLines, margin + 4, innerY)

      y += boxHeight + 4
    })
  }

  // 8. Footer on every page
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setDrawColor(220, 218, 212)
    doc.setLineWidth(0.2)
    doc.line(margin, pageHeight - 11, pageWidth - margin, pageHeight - 11)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(130, 130, 125)
    doc.text('DryRun • Pre-Flight Release Simulation Engine (watsonx.ai Granite 3.3)', margin, pageHeight - 7)
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 7, { align: 'right' })
  }

  const slug = (projectName || 'release').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
  const fileName = `dryrun-release-notes-${slug}-${timestamp}.pdf`

  doc.save(fileName)
}
