'use client';

/**
 * DryRun — Release Notes & Runbook Modal
 * Observability & Developer Experience Agent
 *
 * Generates a clean Markdown PR Release Summary from the live blast-radius
 * and chaos simulation data.  Sections:
 *   1. Impacted Services & APIs
 *   2. High-Risk Dependency Changes
 *   3. Recommended Pre-Release Testing Matrix
 *   4. Rollback Runbook (step-by-step shell commands)
 *
 * "Copy Markdown" button for GitHub PRs / Slack incident channels.
 */

import React, { useState, useCallback, useMemo } from 'react';
import { X, Copy, Check, FileText } from 'lucide-react';
import { useSimulation } from '@/components/visualizer';
import type {
  BlastRadiusReport,
  ChaosSimulationResult,
  ReleaseGateDecision,
  NodeId,
} from '@/types';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const FONT_MONO: React.CSSProperties = {
  fontFamily: '"JetBrains Mono", "Fira Code", monospace',
};

const SEVERITY_MAP: Record<string, string> = {
  CRITICAL: '🔴',
  HIGH: '🟠',
  MEDIUM: '🟡',
  LOW: '🟢',
};

// ---------------------------------------------------------------------------
// Markdown builder
// ---------------------------------------------------------------------------

function buildMarkdown(
  blastReport: BlastRadiusReport | null,
  chaosResult: ChaosSimulationResult | null,
  gateDecision: ReleaseGateDecision | null,
): string {
  const prMeta = blastReport?.changeSet?.prMetadata;
  const title = prMeta?.title ?? 'PR Release Summary';
  const author = prMeta?.author ?? 'unknown';
  const branch = prMeta?.targetBranch ?? 'main';
  const now = new Date().toISOString();

  const blastScore = gateDecision?.blastScore ?? chaosResult?.aggregateRiskScore ?? blastReport?.overallBlastScore ?? 0;
  const severity = gateDecision?.severity ?? 'UNKNOWN';
  const decision = gateDecision?.decision ?? 'PENDING';
  const gate = gateDecision ? `**${decision}**` : '_Not yet evaluated_';
  const sevEmoji = SEVERITY_MAP[severity] ?? '⚪';

  // --- Section 1: Impacted Services & APIs ---
  const topRisky: NodeId[] = blastReport?.topRiskyNodes ?? [];
  const impacts = blastReport?.impacts ?? {};
  const graphNodes = blastReport?.graph?.nodes ?? {};

  const impactedSection = topRisky.length > 0
    ? topRisky
        .slice(0, 8)
        .map((id) => {
          const node = graphNodes[id];
          const impact = impacts[id];
          const score = impact?.impactScore ?? 0;
          const critical = impact?.onCriticalPath ? ' ⚠️ critical-path' : '';
          const label = node?.label ?? id;
          return `| \`${label}\` | \`${id}\` | ${score}/100 |${critical} |`;
        })
        .join('\n')
    : '| _(no data)_ | — | — | |';

  // --- Section 2: High-Risk Dependency Changes ---
  const changedFiles = blastReport?.changeSet?.changedFiles ?? [];
  const addedFiles = blastReport?.changeSet?.addedFiles ?? [];
  const deletedFiles = blastReport?.changeSet?.deletedFiles ?? [];

  const changesSection = [
    ...changedFiles.map((f) => `- ✏️  \`${f}\``),
    ...addedFiles.map((f) => `- ➕ \`${f}\``),
    ...deletedFiles.map((f) => `- ❌ \`${f}\``),
  ].join('\n') || '- _(no file changes recorded)_';

  // --- Section 3: Testing Matrix ---
  const criticalChain = chaosResult?.criticalFailureChain ?? [];
  const testMatrix = criticalChain.length > 0
    ? criticalChain
        .slice(0, 6)
        .map((id) => {
          const node = graphNodes[id];
          const label = node?.label ?? id;
          const prob = chaosResult?.nodeResults?.[id]?.failureProbability ?? 0;
          const pct = Math.round(prob * 100);
          return `| \`${label}\` | Integration | Failure probability: ${pct}% | High |`;
        })
        .join('\n')
    : '| _(run chaos simulation to populate)_ | — | — | — |';

  // --- Section 4: Rollback Runbook ---
  const runbook = gateDecision?.rollbackRunbook ?? [];
  const runbookSection = runbook.length > 0
    ? runbook.map((step, i) => `${i + 1}. \`${step}\``).join('\n')
    : '_No rollback runbook available. Run the watsonx gate evaluation to generate one._';

  // --- Mitigations ---
  const mitigations = gateDecision?.mitigations ?? [];
  const mitigationSection = mitigations.length > 0
    ? mitigations
        .map((m) => `- **${m.priority}** · \`${m.nodeId}\`: ${m.description}`)
        .join('\n')
    : '_No mitigations generated yet._';

  return `# 🚀 DryRun Release Summary

> Generated by **DryRun** · ${now}

## Overview

| Field | Value |
|---|---|
| PR Title | ${title} |
| Author | \`${author}\` |
| Target Branch | \`${branch}\` |
| Blast Score | **${Math.round(blastScore)}/100** |
| Severity | ${sevEmoji} ${severity} |
| Gate Decision | ${gate} |

---

## 1. Impacted Services & APIs

| Service | Node ID | Impact Score | Notes |
|---|---|---|---|
${impactedSection}

---

## 2. High-Risk Dependency Changes

${changesSection}

---

## 3. Recommended Pre-Release Testing Matrix

| Service | Test Type | Risk Signal | Priority |
|---|---|---|---|
${testMatrix}

---

## 4. Recommended Mitigations

${mitigationSection}

---

## 5. Rollback Runbook

${runbookSection}

---

_DryRun · Pre-deployment blast-radius & chaos simulator · Powered by IBM watsonx Granite_
`;
}

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface ReleaseNotesModalProps {
  open: boolean;
  onClose: () => void;
}

// ---------------------------------------------------------------------------
// CopyButton
// ---------------------------------------------------------------------------

function CopyButton({ text }: { text: string }): React.JSX.Element {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback((): void => {
    void navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [text]);

  return (
    <button
      type="button"
      onClick={handleCopy}
      className="flex items-center gap-1.5 px-3 py-1.5 rounded border border-slate-600 hover:border-violet-500 bg-slate-800 hover:bg-violet-900/30 text-slate-300 hover:text-violet-300 text-xs transition-colors"
      style={FONT_MONO}
    >
      {copied ? (
        <>
          <Check className="h-3.5 w-3.5 text-emerald-400" />
          Copied!
        </>
      ) : (
        <>
          <Copy className="h-3.5 w-3.5" />
          Copy Markdown
        </>
      )}
    </button>
  );
}

// ---------------------------------------------------------------------------
// Section heading
// ---------------------------------------------------------------------------

function SectionHeading({ children }: { children: React.ReactNode }): React.JSX.Element {
  return (
    <h3
      className="text-xs font-semibold text-slate-500 uppercase tracking-widest mb-2 mt-5 first:mt-0"
      style={FONT_MONO}
    >
      {children}
    </h3>
  );
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function ReleaseNotesModal({ open, onClose }: ReleaseNotesModalProps): React.JSX.Element | null {
  const { state } = useSimulation();
  const { blastReport, chaosResult, gateDecision } = state;

  const markdown = useMemo(
    () => buildMarkdown(blastReport, chaosResult, gateDecision),
    [blastReport, chaosResult, gateDecision],
  );

  if (!open) return null;

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/70 backdrop-blur-sm z-40"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Modal */}
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Release Notes"
        className="fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 z-50 w-full max-w-2xl max-h-[85vh] bg-slate-900 border border-slate-700 rounded-xl shadow-2xl flex flex-col overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-slate-700 shrink-0">
          <div className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-violet-400" />
            <h2 className="text-sm font-semibold text-slate-200" style={FONT_MONO}>
              Release Notes & Runbook
            </h2>
          </div>
          <div className="flex items-center gap-2">
            <CopyButton text={markdown} />
            <button
              type="button"
              onClick={onClose}
              className="text-slate-500 hover:text-slate-200 transition-colors ml-1"
              aria-label="Close release notes"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Scrollable content */}
        <div className="flex-1 overflow-y-auto px-5 py-5 space-y-1">

          {/* Overview table */}
          <SectionHeading>Overview</SectionHeading>
          <OverviewTable blastReport={blastReport} chaosResult={chaosResult} gateDecision={gateDecision} />

          {/* Impacted Services */}
          <SectionHeading>1 · Impacted Services & APIs</SectionHeading>
          <ImpactedServicesTable blastReport={blastReport} />

          {/* Dependency Changes */}
          <SectionHeading>2 · High-Risk Dependency Changes</SectionHeading>
          <DependencyChangeList blastReport={blastReport} />

          {/* Testing Matrix */}
          <SectionHeading>3 · Pre-Release Testing Matrix</SectionHeading>
          <TestingMatrix chaosResult={chaosResult} blastReport={blastReport} />

          {/* Rollback Runbook */}
          <SectionHeading>4 · Rollback Runbook</SectionHeading>
          <RunbookBlock gateDecision={gateDecision} />
        </div>

        {/* Footer */}
        <div className="shrink-0 px-5 py-3 border-t border-slate-700 flex justify-between items-center">
          <p className="text-xs text-slate-600" style={FONT_MONO}>
            Powered by IBM watsonx Granite
          </p>
          <p className="text-xs text-slate-600" style={FONT_MONO}>
            {new Date().toLocaleString()}
          </p>
        </div>
      </div>
    </>
  );
}

// ---------------------------------------------------------------------------
// Sub-sections
// ---------------------------------------------------------------------------

function OverviewTable({
  blastReport,
  chaosResult,
  gateDecision,
}: {
  blastReport: BlastRadiusReport | null;
  chaosResult: ChaosSimulationResult | null;
  gateDecision: ReleaseGateDecision | null;
}): React.JSX.Element {
  const blastScore = gateDecision?.blastScore ?? chaosResult?.aggregateRiskScore ?? blastReport?.overallBlastScore ?? 0;
  const severity = gateDecision?.severity ?? '—';
  const decision = gateDecision?.decision ?? 'PENDING';
  const sevEmoji = SEVERITY_MAP[severity] ?? '⚪';

  const rows: Array<{ label: string; value: string | React.JSX.Element }> = [
    { label: 'Blast Score', value: `${Math.round(blastScore)} / 100` },
    { label: 'Severity', value: `${sevEmoji} ${severity}` },
    {
      label: 'Gate Decision',
      value: (
        <span
          className={
            decision === 'APPROVED'
              ? 'text-emerald-400 font-bold'
              : decision === 'BLOCKED'
              ? 'text-red-400 font-bold'
              : 'text-slate-500'
          }
        >
          {decision}
        </span>
      ),
    },
    {
      label: 'Affected Nodes',
      value: `${Object.keys(blastReport?.impacts ?? {}).length} nodes`,
    },
    {
      label: 'Critical Paths',
      value: `${blastReport?.criticalPaths?.length ?? 0} paths`,
    },
  ];

  return (
    <div className="rounded-md border border-slate-700 bg-slate-800 overflow-hidden">
      {rows.map((row) => (
        <div
          key={row.label}
          className="flex items-center gap-4 px-4 py-2 border-b border-slate-700/60 last:border-0"
        >
          <span className="w-36 text-xs text-slate-500 shrink-0" style={FONT_MONO}>
            {row.label}
          </span>
          <span className="text-xs text-slate-200" style={FONT_MONO}>
            {row.value}
          </span>
        </div>
      ))}
    </div>
  );
}

function ImpactedServicesTable({ blastReport }: { blastReport: BlastRadiusReport | null }): React.JSX.Element {
  const topRisky = blastReport?.topRiskyNodes ?? [];
  const impacts = blastReport?.impacts ?? {};
  const graphNodes = blastReport?.graph?.nodes ?? {};

  if (topRisky.length === 0) {
    return <EmptyState message="Run a simulation to see impacted services." />;
  }

  return (
    <div className="rounded-md border border-slate-700 overflow-hidden">
      <table className="w-full text-xs" style={FONT_MONO}>
        <thead>
          <tr className="bg-slate-800 text-slate-500 text-left">
            <th className="px-3 py-2 font-semibold">Service</th>
            <th className="px-3 py-2 font-semibold">Node ID</th>
            <th className="px-3 py-2 font-semibold text-right">Score</th>
            <th className="px-3 py-2 font-semibold">Critical Path</th>
          </tr>
        </thead>
        <tbody>
          {topRisky.slice(0, 8).map((id) => {
            const node = graphNodes[id];
            const impact = impacts[id];
            const score = impact?.impactScore ?? 0;
            const critical = impact?.onCriticalPath ?? false;
            const label = node?.label ?? id;
            const scoreColor =
              score >= 80 ? 'text-red-400' : score >= 60 ? 'text-orange-400' : score >= 40 ? 'text-yellow-400' : 'text-emerald-400';
            return (
              <tr key={id} className="border-t border-slate-700/60 hover:bg-slate-800/50">
                <td className="px-3 py-2 text-slate-200">{label}</td>
                <td className="px-3 py-2 text-slate-500">{id}</td>
                <td className={`px-3 py-2 text-right font-bold ${scoreColor}`}>{score}</td>
                <td className="px-3 py-2">
                  {critical ? (
                    <span className="text-yellow-400">⚠️ Yes</span>
                  ) : (
                    <span className="text-slate-600">No</span>
                  )}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

function DependencyChangeList({ blastReport }: { blastReport: BlastRadiusReport | null }): React.JSX.Element {
  const changed = blastReport?.changeSet?.changedFiles ?? [];
  const added = blastReport?.changeSet?.addedFiles ?? [];
  const deleted = blastReport?.changeSet?.deletedFiles ?? [];
  const all = [
    ...changed.map((f) => ({ file: f, type: '✏️  modified' as const })),
    ...added.map((f) => ({ file: f, type: '➕ added' as const })),
    ...deleted.map((f) => ({ file: f, type: '❌ deleted' as const })),
  ];

  if (all.length === 0) {
    return <EmptyState message="No change-set files recorded in this run." />;
  }

  return (
    <ul className="space-y-1">
      {all.map(({ file, type }) => (
        <li key={file} className="flex items-center gap-2 text-xs" style={FONT_MONO}>
          <span className="text-slate-500">{type}</span>
          <code className="text-slate-300 bg-slate-800 px-1.5 py-0.5 rounded border border-slate-700">
            {file}
          </code>
        </li>
      ))}
    </ul>
  );
}

function TestingMatrix({
  chaosResult,
  blastReport,
}: {
  chaosResult: ChaosSimulationResult | null;
  blastReport: BlastRadiusReport | null;
}): React.JSX.Element {
  const criticalChain = chaosResult?.criticalFailureChain ?? [];
  const graphNodes = blastReport?.graph?.nodes ?? {};

  if (criticalChain.length === 0) {
    return <EmptyState message="Run chaos simulation to generate a testing matrix." />;
  }

  return (
    <div className="rounded-md border border-slate-700 overflow-hidden">
      <table className="w-full text-xs" style={FONT_MONO}>
        <thead>
          <tr className="bg-slate-800 text-slate-500 text-left">
            <th className="px-3 py-2 font-semibold">Service</th>
            <th className="px-3 py-2 font-semibold">Test Type</th>
            <th className="px-3 py-2 font-semibold">Risk Signal</th>
            <th className="px-3 py-2 font-semibold">Priority</th>
          </tr>
        </thead>
        <tbody>
          {criticalChain.slice(0, 6).map((id) => {
            const node = graphNodes[id];
            const label = node?.label ?? id;
            const prob = chaosResult?.nodeResults?.[id]?.failureProbability ?? 0;
            const pct = Math.round(prob * 100);
            const priority = pct >= 70 ? 'HIGH' : pct >= 40 ? 'MEDIUM' : 'LOW';
            const priorityColor =
              priority === 'HIGH' ? 'text-red-400' : priority === 'MEDIUM' ? 'text-yellow-400' : 'text-emerald-400';
            return (
              <tr key={id} className="border-t border-slate-700/60 hover:bg-slate-800/50">
                <td className="px-3 py-2 text-slate-200">{label}</td>
                <td className="px-3 py-2 text-slate-400">Integration</td>
                <td className="px-3 py-2 text-slate-400">Failure: {pct}%</td>
                <td className={`px-3 py-2 font-semibold ${priorityColor}`}>{priority}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

function RunbookBlock({ gateDecision }: { gateDecision: ReleaseGateDecision | null }): React.JSX.Element {
  const runbook = gateDecision?.rollbackRunbook ?? [];

  if (runbook.length === 0) {
    return (
      <EmptyState message="Run the watsonx gate evaluation to generate a rollback runbook." />
    );
  }

  return (
    <div className="rounded-md border border-slate-700 bg-[#020617] p-4 overflow-x-auto">
      <pre className="text-xs text-emerald-400 leading-relaxed" style={FONT_MONO}>
        {runbook.map((step, i) => `${String(i + 1).padStart(2, ' ')}. ${step}`).join('\n')}
      </pre>
    </div>
  );
}

function EmptyState({ message }: { message: string }): React.JSX.Element {
  return (
    <p className="text-xs text-slate-600 px-1 py-2" style={FONT_MONO}>
      {message}
    </p>
  );
}
