'use client'

import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { getScoreColor, severityColors, estimateIncidentCost, getRecommendation } from '@/lib/utils'
import type { AIResult } from '@/types'

const typeIcons: Record<string, string> = {
  performance: '⚡',
  security: '🔒',
  architecture: '🏗️',
}

interface RiskReportProps {
  aiResult: AIResult
  stack: string[]
  projectName?: string
  modules?: Array<{ name: string; risk: string; files: number }>
}

export default function RiskReport({ aiResult, stack, projectName, modules }: RiskReportProps) {
  const [displayScore, setDisplayScore] = useState(0)
  const [barWidth, setBarWidth] = useState(0)
  const [expandedIssue, setExpandedIssue] = useState<number | null>(null)

  const score = aiResult.risk_score ?? 0
  const scoreColor = getScoreColor(score)

  useEffect(() => {
    setDisplayScore(0)
    setBarWidth(0)

    let current = 0
    const interval = setInterval(() => {
      current = Math.min(current + 2, score)
      setDisplayScore(current)
      if (current >= score) clearInterval(interval)
    }, 30)

    setTimeout(() => setBarWidth(score), 200)

    return () => clearInterval(interval)
  }, [score])

  const baseCost = estimateIncidentCost(score)

  const handleExportReport = () => {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5)
    const fileName = `risk-report-${projectName || 'project'}-${timestamp}.md`

    const riskLevel = score > 80 ? 'CRITICAL' : score > 60 ? 'HIGH' : score > 40 ? 'MODERATE' : 'LOW'

    let markdown = `# IBM Bob 2.0 — Release Readiness & Deployment Report\n\n`
    markdown += `**Project:** ${projectName || 'Unknown Project'}\n`
    markdown += `**Generated:** ${new Date().toLocaleString()}\n`
    markdown += `**Release Risk Score:** ${score}/100 (${riskLevel})\n`
    markdown += `**Estimated Incident Blast Radius:** $${baseCost.toLocaleString()}\n\n`

    markdown += `## Executive Summary & Risk Assessment\n\n`
    markdown += `${aiResult.summary}\n\n`

    markdown += `## Technology Stack & Dependencies\n\n`
    markdown += stack.map(s => `- ${s}`).join('\n') + '\n\n'

    if (modules && modules.length > 0) {
      markdown += `## Architecture & Module Breakdown\n\n`
      markdown += `| Module | Risk Level | Files |\n`
      markdown += `|---|---|---|\n`
      markdown += modules.map(m => `| ${m.name} | ${m.risk.toUpperCase()} | ${m.files} |`).join('\n') + '\n\n'
    }

    markdown += `## Deployment Requirements & Validation Gates\n\n`
    aiResult.issues?.forEach((issue, idx) => {
      markdown += `### ${idx + 1}. [${issue.severity.toUpperCase()}] ${issue.type.toUpperCase()}\n\n`
      markdown += `**Finding:** ${issue.description}\n\n`
      markdown += `**Impact:** ${issue.impact}\n\n`
      markdown += `**Mitigation Recommendation:** ${getRecommendation(issue.type, issue.severity)}\n\n`
    })

    markdown += `---\n*Generated by IBM Bob 2.0 Release Readiness & Deployment Assistant (IBM watsonx.ai)*\n`

    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8;' })
    const link = document.createElement('a')
    link.href = URL.createObjectURL(blob)
    link.download = fileName
    link.click()
    URL.revokeObjectURL(link.href)
  }

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      gap: '14px',
      height: '100%',
      minHeight: 0,
    }}>
      {/* Header with Export */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingBottom: '10px',
        borderBottom: '1.5px solid #000',
        flexShrink: 0,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <div style={{
            width: '8px',
            height: '8px',
            borderRadius: '50%',
            background: 'hsl(var(--neo-button))',
            boxShadow: '0 0 6px hsl(var(--neo-button))',
          }} />
          <span style={{
            fontFamily: "'Geist', sans-serif",
            fontSize: '12px',
            fontWeight: 700,
            letterSpacing: '0.04em',
            textTransform: 'uppercase',
            color: 'hsl(var(--foreground))',
          }}>
            Release Readiness Report
          </span>
        </div>

        {/* Export button */}
        <button
          onClick={handleExportReport}
          title="Export report as Markdown"
          className="neo-button"
          style={{
            fontSize: '11px',
            padding: '5px 12px',
            background: 'hsl(var(--neo-subtle))',
          }}
        >
          <svg width="13" height="13" viewBox="0 0 14 14" fill="none">
            <path d="M7 1v8M3 6l4 4 4-4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
            <path d="M1 11v1a1 1 0 001 1h10a1 1 0 001-1v-1" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
          </svg>
          Export Release Notes
        </button>
      </div>

      {/* Score display (Neo-panel style) */}
      <div style={{
        textAlign: 'center',
        padding: '20px 16px',
        background: 'hsl(var(--neo-panel-muted))',
        border: '2px solid #000',
        borderRadius: '10px',
        boxShadow: '3px 3px 0 0 #000',
      }}>
        <p style={{
          fontFamily: "'Geist', sans-serif",
          fontSize: '11px',
          fontWeight: 700,
          letterSpacing: '0.08em',
          textTransform: 'uppercase',
          color: 'hsl(var(--muted-foreground))',
          marginBottom: '6px',
        }}>
          Deployment Risk Score
        </p>
        <p style={{
          fontFamily: "'Geist', sans-serif",
          fontSize: '52px',
          fontWeight: 800,
          lineHeight: '1',
          color: scoreColor,
          letterSpacing: '-0.04em',
          marginBottom: '4px',
          transition: 'color 0.3s',
        }}>
          {displayScore}
        </p>
        <p style={{
          fontFamily: "'Geist Mono', monospace",
          fontSize: '13px',
          fontWeight: 600,
          color: 'hsl(var(--muted-foreground))',
        }}>
          / 100
        </p>
      </div>

      {/* Score bar */}
      <div className="damage-bar">
        <div
          className="damage-fill"
          style={{
            width: `${barWidth}%`,
            background: score > 70 ? 'linear-gradient(90deg, #f59e0b, #ef4444)' :
                        score > 40 ? 'linear-gradient(90deg, #22c55e, #f59e0b)' :
                        'linear-gradient(90deg, #22c55e, #4ade80)',
          }}
        />
      </div>

      {/* Executive Summary */}
      <div>
        <p className="sec-header">Executive Summary &amp; Risk Assessment</p>
        <div style={{
          padding: '12px 14px',
          background: 'hsl(var(--neo-input-bg))',
          border: '1.5px solid #000',
          borderRadius: '8px',
          boxShadow: '2px 2px 0 0 #000',
        }}>
          <p style={{
            fontFamily: "'Geist', sans-serif",
            fontSize: '13px',
            lineHeight: '1.6',
            color: 'hsl(var(--foreground))',
          }}>
            {aiResult.summary}
          </p>
        </div>
      </div>

      {/* Cost Estimate */}
      <div style={{
        padding: '14px 16px',
        background: score === 0 ? 'rgba(34,197,94,0.1)' : 'hsl(var(--neo-panel-muted))',
        border: '2px solid #000',
        borderRadius: '8px',
        boxShadow: '2.5px 2.5px 0 0 #000',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
      }}>
        <div>
          <p style={{
            fontFamily: "'Geist', sans-serif",
            fontSize: '11px',
            fontWeight: 700,
            letterSpacing: '0.06em',
            textTransform: 'uppercase',
            color: 'hsl(var(--muted-foreground))',
            marginBottom: '2px',
          }}>
            {score === 0 ? 'Estimated Incident Cost (Deploy Ready)' : 'Estimated Incident Cost'}
          </p>
          <p style={{
            fontFamily: "'Geist', sans-serif",
            fontSize: '24px',
            fontWeight: 800,
            color: score === 0 ? '#16a34a' : '#d97706',
            letterSpacing: '-0.02em',
          }}>
            ${baseCost.toLocaleString()}
          </p>
        </div>
        <div style={{
          width: '36px',
          height: '36px',
          borderRadius: '8px',
          background: score === 0 ? '#4ade80' : 'hsl(var(--neo-button))',
          border: '2px solid #000',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontSize: '18px',
          color: '#000',
          fontWeight: 'bold',
        }}>
          {score === 0 ? '✓' : '⚠'}
        </div>
      </div>

      {/* Issues & Recommendations */}
      <div>
        <p className="sec-header">Issues &amp; Recommendations</p>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {(!aiResult.issues || aiResult.issues.length === 0) && (
            <div style={{
              padding: '20px 14px',
              textAlign: 'center',
              background: 'rgba(34,197,94,0.1)',
              border: '2px solid #000',
              borderRadius: '8px',
              boxShadow: '2px 2px 0 0 #000',
            }}>
              <p style={{
                fontFamily: "'Geist', sans-serif",
                fontSize: '14px',
                fontWeight: 700,
                color: '#16a34a',
                marginBottom: '2px',
              }}>
                ✓ All Release Gates Passed
              </p>
              <p style={{
                fontFamily: "'Geist', sans-serif",
                fontSize: '12px',
                color: 'hsl(var(--muted-foreground))',
              }}>
                No high-risk regressions or CVE vulnerabilities detected. Safe for automated deployment.
              </p>
            </div>
          )}
          {aiResult.issues?.map((issue, i) => (
            <motion.div
              key={i}
              style={{
                padding: '12px 14px',
                background: expandedIssue === i ? 'hsl(var(--neo-panel))' : 'hsl(var(--neo-input-bg))',
                border: '1.5px solid #000',
                borderLeft: `4px solid ${severityColors[issue.severity]}`,
                borderRadius: '6px',
                boxShadow: '2px 2px 0 0 #000',
                cursor: 'pointer',
                transition: 'all 0.15s',
              }}
              initial={{ opacity: 0, x: 8 }}
              animate={{ opacity: 1, x: 0 }}
              whileHover={{ x: 2 }}
              transition={{ delay: i * 0.06 }}
              onClick={() => setExpandedIssue(expandedIssue === i ? null : i)}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '8px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span>{typeIcons[issue.type] || '🔍'}</span>
                  <span style={{
                    fontFamily: "'Geist', sans-serif",
                    fontSize: '13px',
                    fontWeight: 700,
                    color: 'hsl(var(--foreground))',
                  }}>
                    {issue.type.charAt(0).toUpperCase() + issue.type.slice(1)}
                  </span>
                </div>
                <span className={`risk-badge ${issue.severity}`}>
                  {issue.severity.toUpperCase()}
                </span>
              </div>

              <p style={{
                fontFamily: "'Geist', sans-serif",
                fontSize: '12.5px',
                color: 'hsl(var(--foreground))',
                lineHeight: '1.5',
                marginTop: '6px',
              }}>
                {issue.description}
              </p>

              {expandedIssue === i && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  style={{
                    marginTop: '10px',
                    paddingTop: '10px',
                    borderTop: '1px solid hsl(var(--foreground) / 0.12)',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '6px',
                  }}
                >
                  <div>
                    <span style={{
                      fontFamily: "'Geist', sans-serif",
                      fontSize: '11px',
                      fontWeight: 700,
                      color: 'hsl(var(--muted-foreground))',
                      textTransform: 'uppercase',
                    }}>
                      Impact:
                    </span>
                    <p style={{
                      fontFamily: "'Geist', sans-serif",
                      fontSize: '12px',
                      color: 'hsl(var(--foreground))',
                      marginTop: '2px',
                    }}>
                      {issue.impact}
                    </p>
                  </div>
                  <div>
                    <span style={{
                      fontFamily: "'Geist', sans-serif",
                      fontSize: '11px',
                      fontWeight: 700,
                      color: '#16a34a',
                      textTransform: 'uppercase',
                    }}>
                      Recommendation:
                    </span>
                    <p style={{
                      fontFamily: "'Geist', sans-serif",
                      fontSize: '12px',
                      color: 'hsl(var(--foreground))',
                      marginTop: '2px',
                    }}>
                      {getRecommendation(issue.type, issue.severity)}
                    </p>
                  </div>
                </motion.div>
              )}
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  )
}
